version: '3'

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"

  rabbit:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  web:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    image: web:latest  # will build an image using `build` and name it like this.
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
      - rabbit
    links:
      - db:db
      - rabbit:rabbit



  celery:
    image: web:latest  # uses the one above
    command: celery -A backend worker -l info
    depends_on:
      - web
      - db
      - rabbit
    links:
      - db:db
      - rabbit:rabbit
