version: '3'

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"

  rabbit:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./envs/rabbit.env

  web:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    image: web:latest  # will build an image using `build` and name it like this.
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./envs/web.env
      - ./envs/db.env
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
      - rabbit
    links:
      - db:db
      - rabbit:rabbit

  celery:
    image: web:latest  # uses the one above
    command: celery -A backend worker -l info
    depends_on:
      - web
      - db
      - rabbit
    links:
      - db:db
      - rabbit:rabbit

  chat:
    build:
      context: ./chat
      args:
        - NODE_ENV=development
      dockerfile: chat.dockerfile
    command: >
      /bin/bash -c "sleep 10; ../node_modules/.bin/nodemon --legacy-watch --inspect=0.0.0.0:9229 index.js"
    image: chat:latest
    env_file:
      - ./envs/rabbit.env
    environment:
      - NODE_ENV=development
    volumes:
      - ./chat:/opt/app
      - notused:/opt/app/node_modules
    ports:
      - "3000:3000"
      - "9229:9229"
    expose:
      - "3000"
      - "9229"
    depends_on:
      - rabbit
    links:
      - rabbit:rabbit

volumes:
  notused:
